#!/bin/bash

set -ex

# Install is guaranteed to run once per rootfs

echo "Installing kubernetes-node on $JUJU_UNIT_NAME"

apt-get update -qq
apt-get install -qy bridge-utils build-essential libssl-dev libffi-dev python-dev python-pip wget
pip install gsutil path.py

VERSION=`config-get version`
ARCH=`dpkg --print-architecture`
# List the files available for the version and architecture error if none exist.
gsutil ls gs://kubernetes-release/release/$VERSION/bin/linux/$ARCH/

# nsinit is broken / docker exec in 1.3 / noted in kub #1469 nsenter is better
# golang git mercurial bzr

groupadd kubernetes
useradd -d /var/lib/kubernetes \
    -g kubernetes \
    -s /sbin/nologin \
    --system \
    kubernetes

install -d -m 0744 -o kubernetes -g kubernetes /var/lib/kubernetes
install -d -m 0744 -o kubernetes -g kubernetes /etc/kubernetes/manifests

# wait for the world, depends on where we installed it from distro
#sudo service docker.io stop
# or upstream archive
#sudo service docker stop
